name: hwclock-svc
version: '0.3'
summary: Service that reads time from RTC on boot and saves it on shutdown
description: |
  Background service for managing RTC. On boot, the system time is read from RTC.
  On shutdown, the RTC is set to system time.

grade: stable
confinement: strict

apps:
  hwclock:
    daemon: oneshot
    command: sbin/hwclock --hctosys --utc --adjfile=$SNAP_DATA/adjtime
    stop-command: sbin/hwclock --systohc --utc --adjfile=$SNAP_DATA/adjtime
    plugs:
      - time-control
      - network-audit

parts:
  hwclock:
    plugin: nil
    stage-packages:
      - util-linux
